--- #YAML:1.0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-EscalationDates
version: 0.4
abstract: 'Set start and due time automatically when creating a ticket'
author:
  - Benjamin Heisig <bheisig@synetics.de>
license: perl
distribution_type: module
requires:
  Date::Manip: 6.25
  rt: 4.0.0
  perl: 5.10.0
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
provides:
  RT::Extension::EscalationDates:
    file: lib/RT/Extension/EscalationDates.pm
    version: 0.4
  RT::Action::EscalationDates:
    file: lib/RT/Action/EscalationDates.pm
    version: 0.4
no_index:
  directory:
    - etc
    - html
    - inc
    - po
    - t
keywords:
  - RT
  - Request Tracker
  - Escalation
  - SLA
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.benjaminheisig.net/rt-extension-escalationdates.git
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=RT-Extension-EscalationDates
generated_by: Benjamin Heisig <bheisig@synetics.de>
